# Generated by Django 2.1.7 on 2019-09-18 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0002_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platel', to='jogador.Time'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='suspenso',
            field=models.BooleanField(),
        ),
    ]
