# Generated by Django 2.1.7 on 2019-09-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0004_remove_jogador_ida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='suspenso',
            field=models.CharField(max_length=200),
        ),
    ]
