# Generated by Django 2.2.6 on 2019-10-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=800)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
