# Generated by Django 2.2.6 on 2019-10-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
    ]
