# Generated by Django 2.2.6 on 2019-10-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classico', '0002_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(help_text='Adicione apenas o endereço do seu pdf', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(help_text='Adicione apenas o endereço da mídia desejada', max_length=1000),
        ),
    ]
