# Generated by Django 2.2.6 on 2019-10-03 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classico', '0003_auto_20191003_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tipo',
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platel', to='classico.Link'),
        ),
    ]
