# Generated by Django 2.2.6 on 2019-10-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classico', '0005_auto_20191003_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_principal',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='tipo',
            field=models.CharField(choices=[('MC', 'Música'), ('VD', 'Vídeo'), ('QT', 'Questões'), ('LV', 'Livros')], max_length=50),
        ),
    ]
