# Generated by Django 2.2.6 on 2019-10-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classico', '0007_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='descreva',
            field=models.CharField(default='', max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='tipo',
            field=models.CharField(choices=[('DU', 'Dúvida'), ('CO', 'Comentário')], default='DU', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='img_principal',
            field=models.ImageField(blank=True, null=True, upload_to='classico/'),
        ),
    ]
