# Generated by Django 2.1.7 on 2019-09-11 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='The description for your example', max_length=200)),
                ('number', models.CharField(help_text='Insert your example number here', max_length=20)),
                ('balance', models.FloatField(default=0, help_text='Insert your initial balance')),
                ('owner', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Account Owner')),
            ],
        ),
    ]
